config/routes.rb
SmartShop::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'frontend/products#index'

  namespace :frontend do
    root 'products#index'
    resources :products
  end

  namespace :admin, module: "backend" do
    root 'dashboard#index'

    resources :shops, :addresses
    resources :payments, :shipments, :shipping_methods, :shipping_categories
    resources :prototypes, :properties, :option_types
    resources :orders do
      collection do
        post :change_states
      end
    end
    resources :products do
      collection do
        get :trash
      end
      member do
        put :restore
        get :product_properties, :edit_detail
      end
      resources :variants, :images
    end
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

end

app/controllers/backend/addresses_controller.rb
class Backend::AddressesController < Backend::BaseController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.page params[:page]
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to [:admin, @address], notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to [:admin, @address], notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to admin_addresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:name, :zipcode, :phone, :city, :province, :district, :address)
    end
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout "backend"
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  def index
  end
end

app/controllers/backend/images_controller.rb
class Backend::ImagesController < Backend::BaseController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :load_data

  # GET /images
  # GET /images.json
  def index
    @images =
      if @product
        @product.variant_images.page params[:page]
      else
        Image.page params[:page]
      end
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    create_image

    respond_to do |format|
      if @image.save
        format.html { redirect_to admin_product_images_url(@product), notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_product_image_url(@product, @image) }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to admin_product_images_url(@product), notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_product_images_url(@product) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_data
      @product = Product.find(params[:product_id]) if params[:product_id]
      @variants = @product.variants.collect do |variant|
        [variant.sku_and_options_text, variant.id]
      end
      @variants.insert(0, ["ALL", @product.master.id])
    end

    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit!
    end

    def create_image
      @image =
        if request.xhr?
          @product.attachments.new({image: params["Filedata"]})
        else
          Image.new(image_params)
        end
    end
end

app/controllers/backend/option_types_controller.rb
class Backend::OptionTypesController < Backend::BaseController
  before_action :set_option_type, only: [:show, :edit, :update, :destroy]

  # GET /option_types
  # GET /option_types.json
  def index
    @option_types = OptionType.page params[:page]
  end

  # GET /option_types/1
  # GET /option_types/1.json
  def show
  end

  # GET /option_types/new
  def new
    @option_type = OptionType.new
    @option_type.option_values.build
  end

  # GET /option_types/1/edit
  def edit
    @option_type.option_values.build if @option_type.option_values.blank?
  end

  # POST /option_types
  # POST /option_types.json
  def create
    @option_type = OptionType.new(option_type_params)

    respond_to do |format|
      if @option_type.save
        format.html { redirect_to [:admin, @option_type], notice: 'Option type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_types/1
  # PATCH/PUT /option_types/1.json
  def update
    respond_to do |format|
      if @option_type.update(option_type_params)
        format.html { redirect_to [:admin, @option_type], notice: 'Option type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_types/1
  # DELETE /option_types/1.json
  def destroy
    @option_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_option_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_type
      @option_type = OptionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_type_params
      params.require(:option_type).permit(:name, :presentation, :position, option_values_attributes: [:id, :name, :presentation, :_destroy])
    end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BaseController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.by_state(params[:state]).search(params[:keyword]).page params[:page]
    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @orders.to_csv }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_ship_address
    @order.line_items.build
  end

  # GET /orders/1/edit
  def edit
    @order.build_ship_address if @order.ship_address.blank?
    @order.line_items.build if @order.line_items.blank?
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        persist_order_address
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        persist_order_address
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_states
    @orders = Order.where(:id => params[:ids])
    @orders.change_state(params[:state])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:special_instructions, :shipping_method_id, line_items_attributes: [:id, :variant_id, :price, :quantity, :_destroy])
    end

    def address_params
      params.require(:order).require(:ship_address_attributes).permit(:name, :phone, :address)
    end

    def persist_order_address
      @order.persist_address(address_params)
    end
end

app/controllers/backend/payments_controller.rb
class Backend::PaymentsController < Backend::BaseController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.page params[:page]
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to [:admin, @payment], notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to [:admin, @payment], notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.delete
    respond_to do |format|
      format.html { redirect_to admin_payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :order_id, :source_id, :source_type, :payment_method_id, :state, :response_code, :avs_response, :identifier, :cvv_response_code, :cvv_response_message)
    end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::BaseController
  before_action :set_product, only: [:show, :edit, :edit_detail, :update, :destroy, :restore, :product_properties]

  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:keyword]).page params[:page]
  end


  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update_attrs(product_params)
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.delete
    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  def trash
    @products = Product.only_deleted.page params[:page]
    render :file => 'backend/products/index'
  end

  def restore
    @product.restore
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully restored.' }
      format.json { head :no_content }
    end
  end

  def product_properties
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/backend/addresses_helper.rb
module Backend::AddressesHelper
end

app/helpers/backend/base_helper.rb
module Backend::BaseHelper
  def navigation_link(text, url, badges = nil)
    link_to url do
      if badges.is_a?(Hash)
        concat content_tag(:b, badges[:count], class: "badge #{badges[:class]} pull-right")
      end
      concat content_tag(:i, nil, class: 'fa fa-angle-right')
      concat content_tag(:span, text)
    end
  end

  def navigation_link_has_children(text, url)
    link_to url do
      concat content_tag(:i, nil, class: 'fa fa-angle-down text')
      concat content_tag(:i, nil, class: 'fa fa-angle-up text-active')
      concat content_tag(:span, text)
    end
  end

  def active_rules(rules)
    return if rules.blank?
    rules.each do |rule|
      return 'active' if request.fullpath.to_s =~ /\/admin\/#{rule}/
    end
  end

  def show_flash_messages
    return if flash.blank?
    flash.each do |key, value|
      content = content_tag(:button, "x", class: 'close', "data-dismiss" => 'alert')
      # content += content_tag(:h4, "Oh...")
      content += value
      class_name = "alert m m-b-none "
      class_name += (key == :notice ? "alert-success" : "alert-warning")

      return content_tag(:div, content, class: class_name)
    end
  end

  def render_breadcrumb
    render(
      :partial => 'application/breadcrumb',
      :locals => { :title => controller_name.titleize }
    )
  end
end

app/helpers/backend/images_helper.rb
module Backend::ImagesHelper
  def options_text_for(image)
    if image.viewable.is_master?
      'ALL'
    else
      image.viewable.sku_and_options_text
    end
  end
end

app/helpers/backend/option_types_helper.rb
module Backend::OptionTypesHelper
end

app/views/backend/orders/_address.html.haml
%fieldset
  %legend.wrapper-sm
    %i.fa.fa-truck.text-muted.m-r-xs
    Address
  .form-inputs
    = f.simple_fields_for :ship_address do |address|
      = address.input :name
      .line.line-dashed.line-lg.pull-in
      = address.input :phone
      .line.line-dashed.line-lg.pull-in
      = address.input :address
      .line.line-dashed.line-lg.pull-in

app/views/backend/orders/_form.html.haml
= simple_form_for([:admin, @order]) do |f|
  = f.error_notification
  = render :partial => "line_items", :locals => { :f => f }
  %fieldset
    %legend.wrapper-sm
      %i.fa.fa-file-text.text-muted.m-r-xs
      Order
    .form-inputs
      = f.input :shipping_method_id, as: :select, collection: ShippingMethod::METHODS
      .line.line-dashed.line-lg.pull-in
      = f.input :special_instructions
      .line.line-dashed.line-lg.pull-in
  = render :partial => "address", :locals => { :f => f }
  .form-group
    .col-sm-4.col-sm-offset-2
      = link_to "Cancel", admin_orders_path, class: 'btn btn-default'
      = f.button :submit, class: 'btn btn-primary'

app/views/backend/orders/_line_item.html.haml
.nested-fields
  .form-inputs
    = select_product_tag(f.object)
    = f.input :variant_id, as: :select, collection: [[f.object.id, f.object.variant_id]], input_html: { class: 'variant_selecter' }

    = f.input :price, input_html: { class: 'price_input', readonly: true }
    = f.input :quantity, input_html: { value: f.object.quantity || 1 }
  .form-group
    .col-sm-4.col-sm-offset-2
      = link_to_remove_association "remove task", f, class: 'btn btn-danger'
  .line.line-dashed.line-lg.pull-in

app/views/backend/orders/_line_items.html.haml
%fieldset
  %legend.wrapper-sm
    %i.fa.fa-shopping-cart.text-muted.m-r-xs
    Products
  #products
    = f.simple_fields_for :line_items do |line_item|
      = render 'line_item', :f => line_item
    .links
      .form-group
        .col-sm-4.col-sm-offset-2
          = link_to_add_association 'add product', f, :line_items, partial: 'line_item', class: 'btn btn-primary', "data-association-insertion-node" => "#products .links"

app/views/backend/orders/_order.html.haml
%tr{ id: dom_id(order) }
  %td= check_box_tag 'ids[]', order.id
  %td= order.created_at.to_s(:date)
  %td= order.number
  %td= show_state(order.state)
  %td= show_state(order.state)
  %td= show_state(order.state)
  %td= order.ship_address.name
  %td= number_to_money(order.total, :cn)

  %td.col-lg-action
    = link_to edit_admin_order_path(order), class: 'btn btn-default btn-xs' do
      %i.fa.fa-pencil.text-muted
      Edit

app/views/backend/orders/change_states.js.erb
$("#flash_msg").css("display", "none");
$("#flash_msg").html("<%= j render(partial: 'application/flash_message') %>").slideDown();
<% @orders.each do |order| %>
  dom = $("#<%= dom_id(order) %>");
  dom.before("<%= j render(partial: 'order', object: order) %>");
  dom.remove();
  $("#<%= dom_id(order) %>").find("span.label").fadeOut().fadeIn().fadeOut().fadeIn();
<% end %>
setTimeout( function(){ $("#flash_msg .alert").slideUp() }, 5000 );

app/views/backend/orders/edit.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    %section.panel.panel-default
      %header.panel-heading.font-bold Editing order
      .panel-body
        = render 'form'

app/views/backend/orders/index.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    %section.panel.panel-default
      %header.panel-heading.font-bold
        / %span.label.bg-info.pull-right 4 paid
        Listing orders
      #flash_msg.row.m-n
      .row.text-sm.wrapper
        .col-sm-3.m-b-xs
          = form_tag(change_states_admin_orders_path) do
            = select_tag "state", options_for_select(Order::STATES_OPTIONS), class: 'input-sm form-control input-s-sm inline'
            = button_tag 'Apply', class: 'btn btn-sm btn-default', id: 'change_state_btn'

        .col-sm-6.m-b-xs
          / .btn-group{ data: { toggle: 'buttons'} }
          .btn-group
            = order_state_filter_links(params[:state])

        .col-sm-3
          = form_tag(admin_orders_path, method: :get) do
            .input-group
              = hidden_field_tag(:state, params[:state])
              = text_field_tag 'keyword', params[:keyword], class: 'input-sm form-control', placeholder: 'Search'
              .input-group-btn
                = button_tag 'Go', class: 'btn btn-sm btn-default'

      #test.table-responsive
        %table.table.table-striped.b-t.b-light.text-sm
          %thead
            %tr
              %th{ width: '20' }= check_box_tag nil
              %th Completed At
              %th Number
              %th State
              %th Payment State
              %th Shipment State
              %th Custom Info
              %th Total

              %th.col-lg-action

          %tbody
            = render partial: "order", collection: @orders

      %footer.panel-footer
        .row
          .col-sm-4.hidden-xs
            = link_to 'New Order', new_admin_order_path, class: 'btn btn-s-md btn-info btn-rounded'
            = link_to 'Download CSV', admin_orders_path(format: :csv), class: 'btn btn-s-md btn-info btn-rounded'
          .col-sm-4.text-center
            %small.text-muted.inline.m-t-sm.m-b-sm showing 20-30 of 50 items
          .col-sm-4.text-right.text-center-xs
            = paginate @orders

app/views/backend/orders/new.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    %section.panel.panel-default
      %header.panel-heading.font-bold New order
      .panel-body
        = render 'form'

app/views/backend/orders/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @order.number
%p
  %b Item total:
  = @order.item_total
%p
  %b Total:
  = @order.total
%p
  %b State:
  = @order.state
%p
  %b Completed at:
  = @order.completed_at
%p
  %b Special instructions:
  = @order.special_instructions

%p
  %b line item:
  - @order.line_items.each do |item|
    = item.variant.product.name

= link_to 'Edit', edit_admin_order_path(@order)
\|
= link_to 'Back', admin_orders_path