config/routes.rb
SmartShop::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'frontend/products#index'

  namespace :frontend do
    root 'products#index'
    resources :products
  end

  namespace :admin, module: "backend" do
    root 'dashboard#index'

    resources :shops, :addresses
    resources :payments, :shipments, :shipping_methods, :shipping_categories
    resources :prototypes, :properties, :option_types
    resources :orders do
      collection do
        post :change_states
      end
    end
    resources :products do
      collection do
        get :trash
      end
      member do
        put :restore
        get :product_properties, :edit_detail
      end
      resources :variants, :images
    end
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/frontend/base_controller.rb
class Frontend::BaseController < ApplicationController
  layout "frontend"
end

app/controllers/frontend/products_controller.rb
class Frontend::ProductsController < Frontend::BaseController
  def index
    @products = Product.available.page(params[:page]).per(params[:per] || 10)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontend/products_helper.rb
module Frontend::ProductsHelper
end

app/views/frontend/application/_header.html.haml
%header.bg-dark.dk.header.navbar
  .navbar-header.aside-md
    = yield(:back_botton)

    = link_to "#", class: 'navbar-brand', data: { toggle: "fullscreen" } do
      = image_tag("logo.png", class: 'm-r-sm') + "SmartShop"

    = link_to "javascript:void(0)", class: 'btn btn-link visible-xs menu-btn' do
      = content_tag(:i, nil, class: 'fa fa-bars')

app/views/frontend/application/_navigation.html.haml
%aside#nav.bg-light.lter.b-r.aside-md
  %section.vbox
    %section.w-f.scrollable
      %nav.nav-primary.pushy
        %ul.nav
          %li
            = link_to admin_root_path do
              = content_tag(:i, class: 'fa fa-dashboard icon') do
                = content_tag(:b, nil, class: 'bg-danger')
              = content_tag(:span, 'Dashboard')

          %li
            = link_to admin_shops_path do
              = content_tag(:i, class: 'fa fa-envelope-o icon') do
                = content_tag(:b, nil, class: 'bg-primary dker')
              = content_tag(:span, 'Shop')

          %li{ class: active_rules(["products", "option_types", "properties", "prototypes"]) }
            = link_to 'javascript:void(0)' do
              = content_tag(:i, class: 'fa fa-envelope-o icon') do
                = content_tag(:b, nil, class: 'bg-primary dker')
              = content_tag(:span, 'Product')
            %ul.nav.lt
              %li= navigation_link('Product', admin_products_path)
              %li= navigation_link('Option Type', admin_option_types_url)
              %li= navigation_link('Property', admin_properties_path)
              %li= navigation_link('Prototype', admin_prototypes_path)

          %li{ class: active_rules(["orders"]) }
            = link_to admin_orders_path do
              - if Order.working.count > 0
                = content_tag(:b, Order.working.count, class: 'badge bg-danger pull-right')
              = content_tag(:i, class: 'fa fa-envelope-o icon') do
                = content_tag(:b, nil, class: 'bg-primary dker')
              = content_tag(:span, 'Orders')