config/routes.rb
SmartShop::Application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'frontend/products#index'

  namespace :frontend do
    root 'products#index'
    resources :products
  end

  namespace :admin, module: "backend" do
    root 'dashboard#index'

    resources :shops, :addresses
    resources :payments, :shipments, :shipping_methods, :shipping_categories
    resources :prototypes, :properties, :option_types
    resources :orders do
      collection do
        post :change_states
      end
    end
    resources :products do
      collection do
        get :trash
      end
      member do
        put :restore
        get :product_properties, :edit_detail
      end
      resources :variants, :images
    end
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security ..................................................................
  # relationships .............................................................
  has_and_belongs_to_many :properties
  has_and_belongs_to_many :option_types
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/controllers/backend/addresses_controller.rb
class Backend::AddressesController < Backend::BaseController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.page params[:page]
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to [:admin, @address], notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @address }
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to [:admin, @address], notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to admin_addresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:name, :zipcode, :phone, :city, :province, :district, :address)
    end
end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ApplicationController
  layout "backend"
end

app/controllers/backend/dashboard_controller.rb
class Backend::DashboardController < Backend::BaseController
  def index
  end
end

app/controllers/backend/images_controller.rb
class Backend::ImagesController < Backend::BaseController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :load_data

  # GET /images
  # GET /images.json
  def index
    @images =
      if @product
        @product.variant_images.page params[:page]
      else
        Image.page params[:page]
      end
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    create_image

    respond_to do |format|
      if @image.save
        format.html { redirect_to admin_product_images_url(@product), notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: admin_product_image_url(@product, @image) }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to admin_product_images_url(@product), notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_product_images_url(@product) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_data
      @product = Product.find(params[:product_id]) if params[:product_id]
      @variants = @product.variants.collect do |variant|
        [variant.sku_and_options_text, variant.id]
      end
      @variants.insert(0, ["ALL", @product.master.id])
    end

    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit!
    end

    def create_image
      @image =
        if request.xhr?
          @product.attachments.new({image: params["Filedata"]})
        else
          Image.new(image_params)
        end
    end
end

app/controllers/backend/option_types_controller.rb
class Backend::OptionTypesController < Backend::BaseController
  before_action :set_option_type, only: [:show, :edit, :update, :destroy]

  # GET /option_types
  # GET /option_types.json
  def index
    @option_types = OptionType.page params[:page]
  end

  # GET /option_types/1
  # GET /option_types/1.json
  def show
  end

  # GET /option_types/new
  def new
    @option_type = OptionType.new
    @option_type.option_values.build
  end

  # GET /option_types/1/edit
  def edit
    @option_type.option_values.build if @option_type.option_values.blank?
  end

  # POST /option_types
  # POST /option_types.json
  def create
    @option_type = OptionType.new(option_type_params)

    respond_to do |format|
      if @option_type.save
        format.html { redirect_to [:admin, @option_type], notice: 'Option type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_types/1
  # PATCH/PUT /option_types/1.json
  def update
    respond_to do |format|
      if @option_type.update(option_type_params)
        format.html { redirect_to [:admin, @option_type], notice: 'Option type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_types/1
  # DELETE /option_types/1.json
  def destroy
    @option_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_option_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_type
      @option_type = OptionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_type_params
      params.require(:option_type).permit(:name, :presentation, :position, option_values_attributes: [:id, :name, :presentation, :_destroy])
    end
end

app/controllers/backend/orders_controller.rb
class Backend::OrdersController < Backend::BaseController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.by_state(params[:state]).search(params[:keyword]).page params[:page]
    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @orders.to_csv }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_ship_address
    @order.line_items.build
  end

  # GET /orders/1/edit
  def edit
    @order.build_ship_address if @order.ship_address.blank?
    @order.line_items.build if @order.line_items.blank?
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        persist_order_address
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        persist_order_address
        format.html { redirect_to [:admin, @order], notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_states
    @orders = Order.where(:id => params[:ids])
    @orders.change_state(params[:state])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:special_instructions, :shipping_method_id, line_items_attributes: [:id, :variant_id, :price, :quantity, :_destroy])
    end

    def address_params
      params.require(:order).require(:ship_address_attributes).permit(:name, :phone, :address)
    end

    def persist_order_address
      @order.persist_address(address_params)
    end
end

app/controllers/backend/payments_controller.rb
class Backend::PaymentsController < Backend::BaseController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.page params[:page]
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to [:admin, @payment], notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to [:admin, @payment], notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.delete
    respond_to do |format|
      format.html { redirect_to admin_payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :order_id, :source_id, :source_type, :payment_method_id, :state, :response_code, :avs_response, :identifier, :cvv_response_code, :cvv_response_message)
    end
end

app/controllers/backend/properties_controller.rb
class Backend::PropertiesController < Backend::BaseController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.page params[:page]
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to [:admin, @property], notice: 'Property was successfully created.' }
        format.json { render action: 'show', status: :created, location: @property }
      else
        format.html { render action: 'new' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to [:admin, @property], notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to admin_properties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :presentation)
    end
end

app/helpers/backend/addresses_helper.rb
module Backend::AddressesHelper
end

app/helpers/backend/base_helper.rb
module Backend::BaseHelper
  def navigation_link(text, url, badges = nil)
    link_to url do
      if badges.is_a?(Hash)
        concat content_tag(:b, badges[:count], class: "badge #{badges[:class]} pull-right")
      end
      concat content_tag(:i, nil, class: 'fa fa-angle-right')
      concat content_tag(:span, text)
    end
  end

  def navigation_link_has_children(text, url)
    link_to url do
      concat content_tag(:i, nil, class: 'fa fa-angle-down text')
      concat content_tag(:i, nil, class: 'fa fa-angle-up text-active')
      concat content_tag(:span, text)
    end
  end

  def active_rules(rules)
    return if rules.blank?
    rules.each do |rule|
      return 'active' if request.fullpath.to_s =~ /\/admin\/#{rule}/
    end
  end

  def show_flash_messages
    return if flash.blank?
    flash.each do |key, value|
      content = content_tag(:button, "x", class: 'close', "data-dismiss" => 'alert')
      # content += content_tag(:h4, "Oh...")
      content += value
      class_name = "alert m m-b-none "
      class_name += (key == :notice ? "alert-success" : "alert-warning")

      return content_tag(:div, content, class: class_name)
    end
  end

  def render_breadcrumb
    render(
      :partial => 'application/breadcrumb',
      :locals => { :title => controller_name.titleize }
    )
  end
end

app/helpers/backend/images_helper.rb
module Backend::ImagesHelper
  def options_text_for(image)
    if image.viewable.is_master?
      'ALL'
    else
      image.viewable.sku_and_options_text
    end
  end
end

app/views/backend/products/_details_editor_text_area.html.haml
.panel-body
  #epiceditor.tab-content
    #text-area.tab-pane.active
      = text_area_tag 'epiceditor_content', class: 'form-control', rows: 18
    #preview-area.tab-pane
  = f.text_area :detail, class: 'form-control', class: 'hidden'

app/views/backend/products/_details_editor_toolbar.html.haml
%header.panel-heading.pos-rlt
  %ul.nav.nav-tabs
    %li.active
      = link_to("#text-area", data: { toggle: 'tab' }, id: 'editor-edit-btn') do
        = content_tag(:i, nil, class: 'fa fa-pencil') + ' Edit'
    %li
      = link_to("#preview-area", data: { toggle: 'tab' }, id: 'editor-preview-btn') do
        = content_tag(:i, nil, class: 'fa fa-eye') + ' Preview'
  = link_to("#", id: "detail_add_image", class: "detail-add-image pos-abt", data: { product: @product.id }) do
    = content_tag(:i, nil, class: 'fa fa-picture-o') + ' Upload Image'
  %span#uploading_image.pos-abt
    = image_tag("preloaders.gif")
  = file_field_tag :file, id: 'product_upload_images', class: 'hide'

app/views/backend/products/_form.html.haml
= simple_form_for([:admin, @product]) do |f|
  = f.error_notification
  / = @product.errors.full_messages
  %fieldset
    %legend.wrapper-sm
      %i.fa.fa-file-text.text-muted.m-r-xs
      Product
    .form-inputs
      = f.input :name
      .line.line-dashed.line-lg.pull-in
      = f.input :description
      .line.line-dashed.line-lg.pull-in
      = f.input :available_on, as: :string, input_html: { class: 'input-sm input-s datepicker-input', value: @product.available_on, data: { "date-format" => "yyyy-mm-dd" } }
      .line.line-dashed.line-lg.pull-in
      / = f.input :deleted_at
      = f.input :permalink
      .line.line-dashed.line-lg.pull-in
      = f.input :meta_description
      .line.line-dashed.line-lg.pull-in
      = f.input :meta_keywords
      .line.line-dashed.line-lg.pull-in
      = f.association :shipping_category, include_blank: false, wrapper_html: { class: nil }
      .line.line-dashed.line-lg.pull-in
      - if @product.new_record?
        #property_ids.form-group
          %label.col-sm-2.control-label{ for: 'property_ids' }
            Prototype
          .col-sm-10
            = select_tag "product[prototype_id]", options_from_collection_for_select(Prototype.all, "id", "name"), multiple: false, class: 'select required form-control'
        .line.line-dashed.line-lg.pull-in

  = render :partial => "variants", :locals => { :f => f }
  .form-group
    .col-sm-4.col-sm-offset-2
      = link_to "Cancel", admin_products_path, class: 'btn btn-default'
      = f.button :submit, class: 'btn btn-primary'

app/views/backend/products/_side_nav.html.haml
%section.panel.panel-default
  %header.panel-heading.font-bold= @product.sku
  #product_sidenav.list-group.bg-white
    = link_to_unless_current_page edit_admin_product_path(@product), class: 'list-group-item', current_class: 'bg-primary' do
      %i.fa.fa-pencil-square-o.fa-fw
      PRODUCT ATTRIBUTES
    = link_to_unless_current_page edit_detail_admin_product_path(@product), class: 'list-group-item', current_class: 'bg-primary' do
      %i.fa.fa-pencil-square-o.fa-fw
      PRODUCT DETAILS
    = link_to_unless_current_page admin_product_images_path(@product), class: 'list-group-item', current_class: 'bg-primary' do
      %span.badge= @product.variant_images.count
      %i.fa.fa-picture-o.icon-muted.fa-fw
      IMAGES
    = link_to_unless_current_page admin_product_variants_path(@product), class: 'list-group-item', current_class: 'bg-primary' do
      %span.badge= @product.variants.count
      %i.fa.fa-archive.icon-muted.fa-fw
      VARIANTS
    = link_to_unless_current_page product_properties_admin_product_path(@product), class: 'list-group-item', current_class: 'bg-primary' do
      %span.badge= @product.properties.count
      %i.fa.fa-puzzle-piece.icon-muted.fa-fw
      PRODUCT PROPERTIES

app/views/backend/products/edit.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    .row
      .col-lg-9
        %section.panel.panel-default
          %header.panel-heading.font-bold Editing product
          .panel-body
            = form_for([:admin, @product]) do |f|
              = render 'application/error', model: @product
              %fieldset
                %legend.wrapper-sm
                  %i.fa.fa-file-text.text-muted.m-r-xs
                  Product
                .form-inputs
                  .form-group.pull-in.clearfix
                    .col-sm-8
                      %label
                        %abbr(title = 'required') *
                        Name
                      = f.text_field :name, class: 'form-control'
                    .col-sm-4
                      %label
                        %abbr(title = 'required') *
                        Master Price
                      = f.text_field :master_price, class: 'form-control', value: @product.price

                  .form-group.pull-in.clearfix
                    .col-sm-8
                      %label
                        %abbr(title = 'required') *
                        Permalink
                      = f.text_field :permalink, class: 'form-control'
                    .col-sm-4
                      %label
                        Master Sku
                      = f.text_field :master_sku, class: 'form-control', value: @product.sku
                    / .col-sm-3
                    / todo cost price
                    / .col-sm-3
                    / todo cost currency

                  .form-group
                    %label Description
                    = f.text_area :description, class: 'form-control', rows: 4

                  .form-group.pull-in.clearfix
                    .col-sm-8
                      %label Meta Keywords
                      = f.text_field :meta_keywords, class: 'form-control'

                    .col-sm-4
                      %label Available On
                      = f.text_field :available_on, class: 'form-control datepicker-input', value: @product.available_on, data: { "date-format" => "yyyy-mm-dd" }

                  .form-group.pull-in.clearfix
                    .col-sm-8
                      %label Meta Description
                      = f.text_field :meta_description, class: 'form-control'

                    .col-sm-4
                      %label Shipping Category
                      = f.select :shipping_category_id, options_from_collection_for_select(ShippingCategory.all, "id", "name", @product.shipping_category_id), { include_blank: false }, { class: 'select required form-control' }

                  .form-group.pull-in.clearfix
                    .col-sm-8
                      %label Option Types
                      = select_tag "product[option_type_ids]", options_from_collection_for_select(OptionType.all, "id", "name", @product.option_type_ids), multiple: true, class: 'col-xs-12 m-n no-padder'

                %footer.panel-footer.text-right.bg-light.lter
                  = link_to "Cancel", admin_products_path, class: 'btn btn-default'
                  = f.button :submit, class: 'btn btn-primary'

      .col-lg-3
        = render "side_nav"

app/views/backend/products/edit_detail.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    .row
      .col-lg-9
        %section.panel.panel-default
          %header.panel-heading.font-bold Editing product
          .panel-body
            = form_for([:admin, @product]) do |f|
              = render 'application/error', model: @product
              %fieldset
                %legend.wrapper-sm
                  %i.fa.fa-file-text.text-muted.m-r-xs
                  Product
                .form-inputs
                  .form-group
                    %label Details
                    .panel.panel-default
                      = render "details_editor_toolbar"
                      = render "details_editor_text_area", f: f

              %footer.panel-footer.text-right.bg-light.lter
                = link_to "Cancel", admin_products_path, class: 'btn btn-default'
                = f.button :submit, class: 'btn btn-primary', id: 'submit_prodcut_epiceditor'
      .col-lg-3
        = render "side_nav"

app/views/backend/products/edit_details.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    .row
      .col-lg-9
        %section.panel.panel-default
          %header.panel-heading.font-bold Editing product
          .panel-body
            = form_for([:admin, @product]) do |f|
              = render 'application/error', model: @product
              %fieldset
                %legend.wrapper-sm
                  %i.fa.fa-file-text.text-muted.m-r-xs
                  Product
                .form-inputs
                  .form-group
                    %label Details
                    .panel.panel-default
                      = render "details_editor_toolbar"
                      = render "details_editor_text_area", f: f
                %footer.panel-footer.text-right.bg-light.lter
                  = link_to "Cancel", admin_products_path, class: 'btn btn-default'
                  = f.button :submit, class: 'btn btn-primary'

      .col-lg-3
        = render "side_nav"

app/views/backend/products/index.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    %section.panel.panel-default
      %header.panel-heading.font-bold Listing products
      #flash_msg.row.m-n= show_flash_messages
      .row.text-sm.wrapper
        .col-sm-9.m-b-xs
        .col-sm-3
          = form_tag(admin_products_path, method: :get) do
            .input-group
              = text_field_tag 'keyword', params[:keyword], class: 'input-sm form-control', placeholder: 'Search'
              .input-group-btn
                = button_tag 'Go', class: 'btn btn-sm btn-default'

      .table-responsive
        %table.table.table-striped.b-t.b-light.text-sm
          %thead
            %tr
              %th.col-lg-2 Sku
              %th.col-lg-2 Thumbnail
              %th Name
              %th.col-lg-2 Master Price
              %th.col-lg-action

          %tbody
            - @products.each do |product|
              %tr
                %td= product.sku
                %td
                  %span.thumb= thumb_image(product)
                %td= link_to product.name, edit_admin_product_path(product)
                %td= number_to_money(product.price, product.currency)
                %td.col-lg-action
                  = link_to edit_admin_product_path(product), class: 'btn btn-default btn-xs' do
                    %i.fa.fa-pencil.text-muted
                    Edit
                  - if product.destroyed?
                    = link_to restore_admin_product_path(product), method: :put, class: 'btn btn-dark btn-xs', :data => { confirm: 'Are you sure?', dismiss: 'alert' } do
                      %i.fa.fa-undo
                      Restore
                  - else
                    = link_to admin_product_path(product), method: :delete, class: 'btn btn-danger btn-xs', :data => { confirm: 'Are you sure?', dismiss: 'alert' } do
                      %i.fa.fa-trash-o
                      Remove


      %footer.panel-footer
        .row
          .col-sm-4.hidden-xs
            = link_to 'New Product', new_admin_product_path, class: 'btn btn-s-md btn-info btn-rounded'
          .col-sm-4.text-right.text-center-xs
            = paginate @products

app/views/backend/products/new.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    %section.panel.panel-default
      %header.panel-heading.font-bold New product
      .panel-body
        = simple_form_for([:admin, @product]) do |f|
          = f.error_notification
          / = @product.errors.full_messages
          %fieldset
            %legend.wrapper-sm
              %i.fa.fa-file-text.text-muted.m-r-xs
              Product
            .form-inputs
              = f.input :name
              .line.line-dashed.line-lg.pull-in
              = f.input :available_on, as: :string, input_html: { class: 'input-sm input-s datepicker-input', value: @product.available_on, data: { "date-format" => "yyyy-mm-dd" } }
              .line.line-dashed.line-lg.pull-in
              = f.input :permalink
              .line.line-dashed.line-lg.pull-in
              = f.association :shipping_category, include_blank: false, wrapper_html: { class: nil }
              .line.line-dashed.line-lg.pull-in
              = f.input :master_sku
              .line.line-dashed.line-lg.pull-in
              = f.input :master_price
              .line.line-dashed.line-lg.pull-in
              - if @product.new_record?
                #property_ids.form-group
                  %label.col-sm-2.control-label{ for: 'property_ids' }
                    Prototype
                  .col-sm-10
                    = select_tag "product[prototype_id]", options_from_collection_for_select(Prototype.all, "id", "name"), multiple: false, prompt: "Select Prototype", class: 'select required form-control'
                .line.line-dashed.line-lg.pull-in

          .form-group
            .col-sm-4.col-sm-offset-2
              = link_to "Cancel", admin_products_path, class: 'btn btn-default'
              = f.button :submit, class: 'btn btn-primary'

app/views/backend/products/product_properties.html.haml
%section.vbox
  %section.scrollable.padder
    = render_breadcrumb

    .row
      .col-lg-9
        %section.panel.panel-default
          %header.panel-heading.font-bold Editing product
          .panel-body
            = simple_form_for([:admin, @product]) do |f|
              = render :partial => "product_properties", :locals => { :f => f }
              %footer.panel-footer.text-right.bg-light.lter
                = link_to "Cancel", admin_products_path, class: 'btn btn-default'
                = f.button :submit, class: 'btn btn-primary'

      .col-lg-3
        = render "side_nav"